version: '3'

services:
    # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
        container_name: banco-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: curso_vue3_webpack
            MYSQL_ROOT_PASSWORD: dificil123
            MYSQL_PASSWORD: dificil123
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - sistema-gestao-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8899:80
        networks:
            - sistema-gestao-network

networks:
    sistema-gestao-network:
        driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8899/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8989/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root
